export const sampleJapaneseNames = {
  'Sadaharu Oh': '王 貞治',
  'Shigeo Nagashima': '長嶋 茂雄',
  'Hayato Sakamoto': '坂本 勇人',
  'Kazuma Okamoto': '岡本 和真',
  'Koji Uehara': '上原 浩治',
  'Tomoyuki Sugano': '菅野 智之',
  'Alex Ramirez': 'アレックス・ラミレス',
  'Nobuhiro Matsuda': '松田 宣浩',
  'Randy Bass': 'ランディ・バース',
  'Yutaka Enatsu': '江夏 豊',
  'Koji Chikamoto': '近本 光司',
  'Toru Murayama': '村山 実',
  'Akinobu Okada': '岡田 彰布',
  'Tetsuya Yoneda': '米田 哲也',
  'Masayuki Kakefu': '掛布 雅之',
  'Munetaka Murakami': '村上 宗隆',
  'Tetsuto Yamada': '山田 哲人',
  'Wladimir Balentien': 'ウラディミール・バレンティン',
  'Atsuya Furuta': '古田 敦也',
  'Yoshinobu Okugawa': '奥川 恭伸',
  'Tetsuya Iida': '飯田 哲也',
  'Shingo Takatsu': '高津 臣吾',
  'Tsuyoshi Wada': '和田 毅',
  'Kodai Senga': '千賀 滉大',
  'Yuki Yanagita': '柳田 悠岐',
  'Tadahito Iguchi': '井口 資仁',
  'Katsuya Nomura': '野村 克也',
  'Yoshinobu Yamamoto': '山本 由伸',
  'Masataka Yoshida': '吉田 正尚',
  'Kazuhiro Kiyohara': '清原 和博',
  'Hiroki Kokubo': '小久保 裕紀',
  'Yutaka Fukumoto': '福本 豊',
  'Ichiro Suzuki': 'イチロー',
  'Hisashi Yamada': '山田 久志',
  'Tuffy Rhodes': 'タフィ・ローズ',
  'Masahiro Tanaka': '田中 将大',
  'Kazuo Matsui': '松井 稼頭央',
  'Shohei Ohtani': '大谷 翔平',
  'Yu Darvish': 'ダルビッシュ 有',
  'Atsunori Inaba': '稲葉 篤紀',
  'Takuya Asao': '浅尾 拓也',
  'Hiromitsu Ochiai': '落合 博満',
  'Daisuke Yamai': '山井 大介',
  'Kosuke Fukudome': '福留 孝介',
  'Kenshin Kawakami': '川上 憲伸',
  'Shinichi Sato': '佐藤 真一',
  'Koji Yamamoto': '山本 浩二',
  'Seiya Suzuki': '鈴木 誠也',
  'Kris Johnson': 'クリス・ジョンソン',
  'Takahiro Arai': '新井 貴浩',
  'Tomonori Maeda': '前田 智徳',
  'Roki Sasaki': '佐々木 朗希',
  'Katsuya Kakunaka': '角中 勝也',
  'Kazuya Fukuura': '福浦 和也',
  'Kazuhiro Wada': '和田 一浩',
  'Koji Akiyama': '秋山 幸二',
  'Daisuke Matsuzaka': '松坂 大輔',
  'Takeya Nakamura': '中村 剛也',
  'Kazuhisa Inao': '稲尾 和久',
  'Takuro Ishii': '石井 琢朗',
  'Takahiro Saeki': '佐伯 貴弘',
  'Shun Yamaguchi': '山口 俊',
  'Daisuke Miura': '三浦 大輔',
  'Yoshitomo Tsutsugo': '筒香 嘉智',
  'Hideto Asamura': '浅村 栄斗',
};
